package com.quickcleanpro.phonecleaner.app.navigation.feature
enum class FeatureKey {
    JUNK_CLEAN,
    ANTI_VIRUS,
    APP_LOCK,
    DEVICE_INFO,
    BATTERY_INFO,
    APP_USAGE,
    NOTIFICATION_CLEANER,
    WHATSAPP_CLEANER,
    NETWORK_USAGE,
    NETWORK_SCAN,
    NETWORK_SPEED,
    PHOTOS,
    SIMILAR_PHOTOS,
    PHOTO_PRIVACY,
    SCREENSHOTS,
    VIDEOS,
    AUDIOS,
    LARGE_FILES,
    DUPLICATE_FILES,
    DOCUMENTS,
}
